- name: Waiting for SSH connection
  ansible.builtin.wait_for_connection:

- name: Set unattended-upgrades update frequency to 0
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: "^\\s*\\bAPT::Periodic::Unattended-Upgrade\\b"
    line: "APT::Periodic::Unattended-Upgrade \"0\";"
    state: present

- name: Stop the unattended-upgrades service
  ansible.builtin.service:
    name: unattended-upgrades
    state: stopped

- name: Run apt update
  ansible.builtin.apt:
    update_cache: yes

- name: Install dependencies
  ansible.builtin.package:
    name:
      - apt-transport-https
    state: present

- name: Get distribution codename
  ansible.builtin.command: "lsb_release -c"
  register: lsb_release_output

- name: Store codename in a variable
  set_fact:
    distribution_codename: "{{ lsb_release_output.stdout_lines[0].split()[-1] }}"
  when: lsb_release_output.stdout_lines

- ansible.builtin.debug:
    msg: "Distribution codename: {{ distribution_codename }}"

- name: Create source.list.d tor.list
  ansible.builtin.copy:
    content: |
       deb     [signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https://deb.torproject.org/torproject.org {{ distribution_codename }} main
       deb-src [signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https://deb.torproject.org/torproject.org {{ distribution_codename }} main
    dest: /etc/apt/sources.list.d/tor.list

- name: Download Tor Project GPG key
  ansible.builtin.shell: >
        wget -qO- https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc |
        gpg --dearmor |
        sudo tee /usr/share/keyrings/tor-archive-keyring.gpg >/dev/null

- name: Run apt update
  ansible.builtin.apt:
    update_cache: yes


